### ISSUE TITLE
Flickering on zoom level change

### ISSUE THREAD

**Issue by peleserg** [Equify/react-datasheet-grid#102]
When zoom in browser is set to specific values (80%, 67%...) scrollbars continuously appears and disappears. Issue was reproduced on Chrome and Edge.

![DatasheetFlickering](https://user-images.githubusercontent.com/6541409/148724775-7fd0b626-e582-43f7-8b02-a2282940e7ee.gif)

**Comment by nick-keller** [comment]
Thanks for the feedback @peleserg 
Not an easy problem, I will look into it, if anyone has any suggestion I'd gladly take it into account.

**Comment by dmikoss** [comment]
Hi @nick-keller .
I installed (npm i) 3.6.1 version in my project, but in useColumnWidths.js in dist folder has older source, without applied flickering fix.
![image](https://user-images.githubusercontent.com/860146/149313955-3c3a996c-9406-45d2-850f-13b31988d85b.png)
