### ISSUE TITLE
RowKey prop not present in dist folder when installing the package at 4.4.0

### ISSUE THREAD

**Issue by Tibs7777** [Equify/react-datasheet-grid#155]
Been finding since the version bump to 4.4.0 with the rowKey that it's not actually showing up anywhere in my dist folder when I npm install the package so I can't use it. Unsure if this is something my end if it's just related to the package build process. 

Below is taken from a freshly created app that's installed the package at 4.4.0.
![fH4EZeH](https://user-images.githubusercontent.com/66207372/168554653-c99ab38a-80dd-4349-a4dd-e189ea858665.png)

**Comment by nick-keller** [comment]
Thanks for the repport @Tibs7777 , now fixed in 4.4.1 ;)
