### ISSUE TITLE
+ Add # rows button triggers many event handlers !

### ISSUE THREAD

**Issue by msgfxeg** [Equify/react-datasheet-grid#18]
Hi,
I have integrated react-datasheet-grid with my system successfully and it works great actually. However, upon clicking on the + Add # rows (bottom bar) of the component it calls event handlers that it does not supposed to call and messes my UI (i.e. triggers an alert in a validation method inside an on submit event handler! also shrinks/closes/collapses bootstrap accordion component) which is very weird.

My guess is that this + Add # rows button calls an event handler which I could not figure it out nor could not find it in the documentation  to be able to stop this mess!

So, Kindly help me
PS: I think that as a hacky solution to my case I need to add e.stopPropagation() on that button event handler however I could not figure out how to access that event handler!

**Comment by nick-keller** [comment]
Hey @msgfxeg ,
Thx for your feedback, fix is published in 1.0.7 ;)
Happy hacking!

**Comment by msgfxeg** [comment]
Hey @nick-keller,
Thx for your reply I will try the new version.
I have managed to fix my problem in a hacky way by inserting the component in an unnecessary from with a dummy submit event handler that prevents propagation as follows:
<form onSubmit={(e) => { e.preventDefault(); e.stopPropagation(); }} >
  <DataSheetGrid ... />
</form>
;)

**Comment by nick-keller** [comment]
With `v1.0.7` you should not need to wrap it into a form ;)

**Comment by msgfxeg** [comment]
That is very good indeed as React is complaining :)
