### ISSUE TITLE
Column sorting

### ISSUE THREAD

**Issue by hbasaraner** [Equify/react-datasheet-grid#19]
Hello. 👋🏻 Is there any property for column sorting? If isn't, will be added in future updates? Thanks.

**Comment by nick-keller** [comment]
Hi @hbasaraner,
Nothing planned on that matter yet, could you pitch your idea?

**Comment by hbasaraner** [comment]
> Hi @hbasaraner,
> Nothing planned on that matter yet, could you pitch your idea?

Hi. I'm just developing an application to show my Excel data. It contains hundreds of data, so it's hard to find what I want exactly. Not a big problem right now, but it might be good for me. By the way, I'm implementing a new column type to your project. I'll glad if I make a contribution.

**Comment by nick-keller** [comment]
If you have a precise use-case with an API idea feel free to share, will gladly consider it for future releases ;)
