### ISSUE TITLE
Select column

### ISSUE THREAD

**Issue by hbasaraner** [Equify/react-datasheet-grid#21]
Hello again, with my new idea. :)

Here is a new column type suggestion for selecting item. I changed `<input>` tag to `<select>` in the screenshot. 

![Screen Shot 2021-01-14 at 10 27 05](https://user-images.githubusercontent.com/7539129/104558105-57307580-5653-11eb-950f-5ac5392a92e9.png)

But I'm confused about how to integrate this column type to this project. I'm new in React & Typescript. So it may take a time to develop this. But if there will be update, I'll post it in here. 👍🏻

**Comment by nick-keller** [comment]
Have a look in `src/columns`, duplicate a file, and work from here. It should be pretty straight forward to implement.
Then make a pull request. ;)

**Comment by nick-keller** [comment]
An example is available here: https://react-datasheet-grid.netlify.app/docs/examples/implementing-select/
