### ISSUE TITLE
Holding shift to highlight multiple rows

### ISSUE THREAD

**Issue by sdkrocks** [Equify/react-datasheet-grid#25]
Hi!
Currently the ability to click and drag to copy multiple rows exists. I was wondering if it would be a possibility to add the feature of holding shift to select all rows from the first clicked to the last.

This would also go along with holding ctrl, to select multiple rows not next to each other. 

This would make data easier to copy and paste to and from other places.

**Comment by nick-keller** [comment]
Hey @sdkrocks ,
It is already possible to SHIFT + Arrow, I think adding SHIFT + CLICK is feasible soon.
But handling multi-selection is too complex and out of the scope of this package.

**Comment by sdkrocks** [comment]
> Hey @sdkrocks ,
> It is already possible to SHIFT + Arrow, I think adding SHIFT + CLICK is feasible soon.
> But handling multi-selection is too complex and out of the scope of this package.

Understood! Awesome. Thanks for considering it!

**Comment by nick-keller** [comment]
Available in V2
