### ISSUE TITLE
Callback when cell is selected

### ISSUE THREAD

**Issue by UnleashedMV** [Equify/react-datasheet-grid#30]
Hello, 

is ther a function to pass to the DataGrid, when i click into a cell, to get the information from the cell?

With best regards.

**Comment by nick-keller** [comment]
It does not support callbacks for this event. Out of curiosity, what is the usecase?

**Comment by nick-keller** [comment]
Actually you can handle this in the cell component: 
```tsx
const MyComponent = ({ active }) => {
  useEffect(() => {
    if (active) {
      // Do something
    }
  }, [active])
}
```
