### ISSUE TITLE
Grid crashes when columns are modified at runtime

### ISSUE THREAD

**Issue by puffedo** [Equify/react-datasheet-grid#36]
Hi, thanks for the great work!

I was trying to use your grid in an application in which column definitions can change at runtime. Unfortunately, modifying columns crashes the grid. I could reproduce this problem with a minimal example here:

https://codesandbox.io/s/green-monad-7svl0?file=/src/App.tsx

Luckily, there is a workaround (contained in the example above), but it's not very elegant. 

Is this a bug or is react-datasheet-grid designed to only work with a static set of columns?

**Comment by nick-keller** [comment]
Definitely a bug, thx for the report!
I will fix it soon.

**Comment by nick-keller** [comment]
Fixed in V2

**Comment by larissa-n** [comment]
Did you ever consider incorporating column props into the memo condition as well? Currently you need to force a rerender with something like key={columns.length} to modify columns. Thanks!

**Comment by nick-keller** [comment]
This is already supported, full explanation [in the doc](https://react-datasheet-grid.netlify.app/docs/performance/static-vs-dynamic)
