### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by drixta** [Equify/react-datasheet-grid#38]
Amazing job guys for building this product, overall it was super smooth and the performance is very impressive.

I'm personally curious about the feature roadmap for this product, specifically for native spreadsheet interactions available on Google Sheets/Excel like the following:
- Ctrl/Command + Click for multiple disjointed cell selection
- Select + Drag to copy values across multiple cells
- Drag to resize columns and rows

Thank you very much, I'm planning to use react-datasheet-grid and missing these features, it's holding me back from committing to it, otherwise, I love the development experience of it.

**Comment by nick-keller** [comment]
Hello @drixta ,
Thanks for your feedbacks ;)
Performance-wise, version 2 is coming up as described in #37 which should drastically improve performance.
Now concerning your points, I'm happy to discuss and find the best approach (this will help speeding up development in the right direction):

### Ctrl/Command + Click for multiple disjointed cell selection
I haven't looked into it as I do not see the use-case, but I would be more than happy to think about it if you can justify it with some real-world example. 

My first impression is that it makes everything very complicated regarding copy / pasting and Select + Drag. I guess just testing it in Excel might shine some light on the subject.

### Select + Drag to copy values across multiple cells
Definitely a very demanded feature that I plan to include in V2. Today you can copy a value and paste it on several rows already, but everyone is instinctively trying to drag the corner... 

There might be some tricky use cases: 
- It only makes sense to drag vertically right? DSG is column-based and dragging a date into a number for instance does not make sense.
- What if you select several rows and drag it down? Should just duplicate the last value? 

Not quite sure how the API should allow customizing the behavior of this.

### Drag to resize columns and rows
Today column size is defined in flex with a min and max width. How do you imagine the API would be to support this resizing feature?

**Comment by drixta** [comment]
> ### Ctrl/Command + Click for multiple disjointed cell selection
> I haven't looked into it as I do not see the use-case, but I would be more than happy to think about it if you can justify it with some real-world example.

For this feature, I would agree that even though the feature exists for Excel and Google Sheet, it isn't a critical one for my use case.

> ### Select + Drag to copy values across multiple cells
> Definitely a very demanded feature that I plan to include in V2. Today you can copy a value and paste it on several rows already, but everyone is instinctively trying to drag the corner...
> * It only makes sense to drag vertically right? DSG is column-based and dragging a date into a number for instance does not make sense.
> * What if you select several rows and drag it down? Should just duplicate the last value?

I think the drag should just copy the underlying data as string and let the renderer decides on what to do with the data.

> Not quite sure how the API should allow customizing the behavior of this.

I don't think for now, you'll need any customization for this feature.

> ### Drag to resize columns and rows
> Today column size is defined in flex with a min and max width. How do you imagine the API would be to support this resizing feature?

You could potentially do `flex: 0 0 100px` for columns to set the width. As for api, `width` and `defaultWidth` could be 2 attributes to add to the column data.

**Comment by Limurezzz** [comment]
Hello @nick-keller,
This is absolutely great work!

I was thinking about using the React Table library https://react-table.tanstack.com/
But now I think I will keep my eyes on your solution. 

But in order to outbid React Table I think we all need more basic features like React Table has. 
For example: sub-headers, expanding, row drag&drop (actually with your rows copy/paste it is now possible)
See more example: https://react-table.tanstack.com/docs/examples/basic

Thanks for your effort.

**Comment by nick-keller** [comment]
Thanks for the feedbacks,
Today the best way to help (besides writing PRs of course 😜 ) would be to write some specs for the features you think are missing.
The most difficult part I think is designing the API trying to balance simplicity and flexibility.

I'll open some issues, feel free to contributes with ideas!

**Comment by nick-keller** [comment]
@Limurezzz can you please create issues for "sub-headers" and "expanding", I'm not sure I understand what you need.
