### ISSUE TITLE
Copying from excel is overwritting an extra row with blanks

### ISSUE THREAD

**Issue by rogerfn** [Equify/react-datasheet-grid#39]
Hi, 

I want to report a small issue that probably has to do with the way that excel is putting the data into the clipboard
![Animation2](https://user-images.githubusercontent.com/6075200/124612761-e2582e80-de72-11eb-8d86-3bb2399060ed.gif)

Cheers,

**Comment by nick-keller** [comment]
Thanks for your report, the entire pasting parsing algorithm should be re-written to support line return in cells.
I'm not sur I understand why Excel is adding an empty line, I've never seen this issue, I will investigate.

**Comment by rogerfn** [comment]
It is actually just a new line at the end that is messing everything around. I created a PR to delete any new line at the end of the copied text

**Comment by nick-keller** [comment]
Fixed and live on npm!
