### ISSUE TITLE
Feature proposal: programmatic grid control

### ISSUE THREAD

**Issue by weevolve-dev** [Equify/react-datasheet-grid#43]
Hi, I'd like to propose *Programmatic Grid Control* as a new feature that might be useful for many typical use cases and is (hopefully) easy to implement:

Motivation
---
In many applications, a data grid is used in conjunction with other UI elements that represent the same data in a different way, e.g. charts that visualize the grid data. It would be great if these UI components could interact programmatically with the data grid, for example:
* a click on an element in a scatter plot will set the focus to the corresponding cell in the grid
* a click on a bar in a bar chart will select the corresponding row or column in the data grid
* in the example below, each 'ring segment' represents a table cell. A click on a ring segment would set the focus to this table cell
 
![image](https://user-images.githubusercontent.com/58294836/125021687-5712af00-e0a5-11eb-9e9a-56a78997e9ad.png)

In order to allow such interaction between UI components, the data grid must expose some internal functions for programmatic access from outside.

API
---
To keep it simple, this feature could be implemented by exposing already existing functions via a `forwardRef` and `useImperativeHandle` like this:

*DataSheetGrid.tsx:*
```js
// ...

export const DataSheetGrid = forwardRef((props, ref) => {

//...

  useImperativeHandle(
    ref,
    () => ({
      activeCell,
      setActiveCell,
      selectionCell,
      setSelectionCell
    })
  );

// ...

}
```

*Caller:*
```js
// create a ref to the data grid
const gridRef = useRef();

<DataSheetGrid 
  ref={gridRef} 
  data={data}
  onChange={setData}
  columns={columns} />

// ...

// use the ref to access the grid from somewhere else in the code
<button
  onClick = {()=> gridRef.setActiveCell({x:0, y: 0})}>
  Highlight the first cell
</button>


```

**Comment by nick-keller** [comment]
Sounds like a must have, thanks for the detailed specs. Will try to implement it ASAP.

**Comment by nick-keller** [comment]
@weevolve-dev this is now available in version `2.0.8`, doc is up to date here: https://react-datasheet-grid.netlify.app/docs/api-reference/ref/

**Comment by weevolve-dev** [comment]
Great, thanks a lot!

**Comment by nick-keller** [comment]
By the way, any feedback is welcomed.
We could expose more controls, we could also have some `onActiveCellChanges` kind of props, and so on... So any suggestion with a practical use case is welcomed ;)
