### ISSUE TITLE
Scrollbar shown on page refresh

### ISSUE THREAD

**Issue by dmikoss** [Equify/react-datasheet-grid#46]
Hi.
If we make refresh to browser page (F5), scrollbar shown for small period of time.

Example:
![scrollbar-bug](https://user-images.githubusercontent.com/860146/129702628-1d2c97ed-74d7-4da2-aede-c1c05ba31687.gif)

**Comment by nick-keller** [comment]
Thx I'll try to look into it, looks like the initial height computation is off by a pixel...

**Comment by nick-keller** [comment]
This is now fixed in 3.2.3
