### ISSUE TITLE
Accessibility issues (focus by keyboard)

### ISSUE THREAD

**Issue by dmikoss** [Equify/react-datasheet-grid#48]
We cant to change focus from table to prevous or next element (button or other focusable html element) by tab, shift+tab keys.

**Comment by nick-keller** [comment]
That is right, I'm going to make sure:
- `Shift + Tab` from the top-left cell will focus previous focusable element
- `Tab` from the bottom-right cell will focus next focusable element

Thx for the feedback ;)

**Comment by nick-keller** [comment]
Hey @dmikoss ,
This is now available in 3.1.2 ;)
