### ISSUE TITLE
Bug - Select Column Example - Tab Function

### ISSUE THREAD

**Issue by rdick** [Equify/react-datasheet-grid#49]
I want to start by saying I love your library and it will be very big very soon!

On "Select Column Example" there is a bug .

Step:
- Go to final completed example for "Select Column Example" (bottom of page) 
- https://react-datasheet-grid.netlify.app/docs/examples/implementing-select#using-with-multiple-columns
- Enter in A Value in Select Column then press tab to accept value
- **ERROR VIDEO - https://www.loom.com/share/dc94c90ce38d4dd7be0150a001bf797b**
- When you press tab it skips one column right then when column down
- IT SHOULD ONLY SKIP ONE COLUMN RIGHT

Thanks,

Any help with this would be greatly appreciated

**Comment by nick-keller** [comment]
Thx for the report @rdick ;)
I would assume this comes from the `onChange` of the select. It updates the value and then calls `stopEditing`, which goes to the next line by default. Then the component catches the tab key and moves right.

To solve the issue, you can update the `onChange` of the select to specify `nextRow: false`:
```diff
- setTimeout(stopEditing, 0)
+ setTimeout(() => stopEditing({ nextRow: false }), 0)
```

**Comment by rdick** [comment]
Thanks Nick! Issue Solved

For anyone just wanting to copy and paste here is the React Select Component

`
<Select 
            ref={ref}
            styles={{
                container: (provided) => ({
                    ...provided,
                    flex: 1,
                    alignSelf: 'stretch',
                    pointerEvents: focus ? undefined : 'none',
                }),
                control: (provided) => ({
                    ...provided,
                    height: '100%',
                    border: 'none',
                    boxShadow: 'none',
                    background: 'none',
                }),
                indicatorSeparator: (provided) => ({
                    ...provided,
                    opacity: 0,
                }),
                indicatorsContainer: (provided) => ({
                    ...provided,
                    opacity: active ? 1 : 0,
                }),
                placeholder: (provided) => ({
                    ...provided,
                    opacity: active ? 1 : 0,
                }),
            }}
            isDisabled={columnData.disabled}
            value={columnData.choices.find(({ value }) => value === rowData) ?? null}
            menuPortalTarget={document.body}
            menuIsOpen={focus}
            onChange={({ value }) => {
                setRowData(value);
                setTimeout(stopEditing({ nextRow: false }), 0);
            }}
            onMenuClose={() => stopEditing({ nextRow: false })}
            options={columnData.choices}
        />

`
