### ISSUE TITLE
Pasting oversized data causes crash - calling typeCheck on nonexistent cells

### ISSUE THREAD

**Issue by larissa-n** [Equify/react-datasheet-grid#74]
![react-datasheet-grid](https://user-images.githubusercontent.com/37840830/139482878-950b92a9-2d8c-4670-bbd2-649c03c515ba.gif)

Cannot paste clipboard data with more columns than DataSheetGrid without crashing. Is there any way to intercept this and check if elements will make it into the table, to make the component more robust?

Test on [Codesandbox](https://codesandbox.io/s/dreamy-sun-9rhl0?file=/src/App.js) or [Demo website](https://react-datasheet-grid.netlify.app/docs/api-reference/built-in-columns).

**Comment by nick-keller** [comment]
Hello @larissa-n , thanks for the repport.
I will fix this in a few hours, I'll let you know.

**Comment by nick-keller** [comment]
Fix available in 3.3.4
