### ISSUE TITLE
Custom shortcuts for the Grid

### ISSUE THREAD

**Issue by YordinsonPolar** [Equify/react-datasheet-grid#86]
I need to use custom shortcuts, is there a way to control shortcuts?

**Comment by nick-keller** [comment]
It really depends on your goal, can you be more specific on what you are trying to achieve?

**Comment by YordinsonPolar** [comment]
I want to use shortcuts, like ctrl + tab in a highlighted cell and a modal opens with the data of that cell

**Comment by nick-keller** [comment]
This is not related to DSG, but you can add an event listener on the document for key down and use it to trigger a callback when the user presses a particular set of keys.
