### ISSUE TITLE
Remove CSS import in order to support Next.js

### ISSUE THREAD

**Issue by iacobfred** [Equify/react-datasheet-grid#99]
Hi, I'm trying to use this component in a Next.js application, but the code fails to compile due to this error:
```
./node_modules/react-datasheet-grid/dist/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-datasheet-grid/dist/components/DataSheetGrid.js
```
See https://nextjs.org/docs/messages/css-npm 

Would it be possible to remove the CSS import and allow developers to instead import the CSS in their own projects (to control how the CSS is consumed/injected)?

**Comment by nick-keller** [comment]
Sounds reasonable. But the doc needs to be updated, and that sounds like a breaking change for existing users, how do you propose we can handle that?

**Comment by nick-keller** [comment]
Closing this issue as it seems dead

**Comment by cholazzzb** [comment]
> Sounds reasonable. But the doc needs to be updated, and that sounds like a breaking change for existing users, how do you propose we can handle that?
Hello, @nick-keller.
I think this can be solved with css in js or style = {{}} in the component. However, I see that the library makes use of CSS variables. Maybe the CSS variable can be moved inside the component with js as well? What are your thoughts?

**Comment by lveillard** [comment]
Had this same issue and had to drop this lib :(

**Comment by LoncaSorin** [comment]
Yea, me too.. :(

**Comment by cholazzzb** [comment]
Let's discuss and [Proposed Solution](https://github.com/Equify/react-datasheet-grid/discussions/110) in the discussions tab @lveillard @LoncaSorin

**Comment by nick-keller** [comment]
Hello @iacobfred @cholazzzb lveillard,
This will be live in less than 24h, this will be a v4 as it is not backward compatible.

**Comment by nick-keller** [comment]
Alright, 4.0.0 is live ;)
